### PR TITLE
-Also Fixed issue related to DragNDropSimpleadapter background data list...

### PR DESCRIPTION
**Pull request by krazykira**
-Fixed issue ( notifyDataSetChanged was not working when background data attached with DragNDropSimpleadapter was changed). This was causing the app to crash due to index out of bound exception.
- Updated Support Library Version to 21.0.3
- Updated Android Target Version to 5.0.1

### CODE REVIEW

**Comment by krazykira** [comment]
##### If there is any problems understanding what was fixed then i assume you try to run the DragNDropSimpleAdapter  with below class. You will notice that it will crash.<h5>
~~~~ Java
public class DragListActivity extends Activity {
	private DragNDropListView lv_list;
	private DragNDropSimpleAdapter mAdapter;
	private ArrayList<Map<String, Object>> items;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		setContentView(R.layout.activity_draglist);
		super.onCreate(savedInstanceState);
		initUi();
		fillStudentList();
	}

	private void initUi() {
		items = new ArrayList<>();
		lv_list = (DragNDropListView) findViewById(R.id.lv_dragList);
		mAdapter = new DragNDropSimpleAdapter(this, items, R.layout.listitem_drag_n_drop, new String[] { "name" },
				new int[] { R.id.text }, R.id.handler);
		lv_list.setDragNDropAdapter(mAdapter);

	}

	private void fillStudentList() {
		for (int i = 0; i < 20; i++) {
			HashMap<String, Object> item = new HashMap<String, Object>();
			item.put("name", "Name " + i);
			item.put("_id", "id " + i);

			items.add(item);
		}
		mAdapter.notifyDataSetChanged();

	}
}

~~~~

**Comment by krazykira** [comment]
@fidanov @gipi @vlyutskanov  could you guys take a look at it and merge it ?

**Comment by fidanov** [comment]
Thanks!

**Comment by krazykira** [comment]
@fidanov  ur welcome. Glad to help :)

**Pull request merged**
